[2024-06-18] heewon #97
ksumini/Algorithm-Study2.0 pull request #105
Opened 2024-06-16 13:25 UTC by HeewonKwak

## 함수 설명
- `timetomin`: 시간 문자열 (hh:mm 형식)을 분 단위 정수형으로 변환하는 함수입니다.

## 접근 방식
- 호텔 예약 정보를 대소 비교 가능한 분의 형태로 전환한다. 퇴실 시간은 10분 추가
- 호텔 예약 정보를 시작 시간을 기준으로 정렬한다.
- 차례대로 룸에 배정을 한다.
    - 룸에 들어오는 정보는 heap을 이용하여 퇴실 시간 기준으로 정렬한다.
    - 새로운 손님이 들어올 때
        - 대실 중이고 기존 손님의 퇴실 시간 <= 새로운 손님의 시작 시간이면
            - 기존 손님은 퇴실
        - 새로운 손님은 대실
        - 최대 대실 수 확인

<html>
<body>
<pre class="console-content" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1.3125rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: Hack, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; overflow: auto; display: block; border: none; background-color: rgb(38, 55, 71); border-radius: 0px; word-break: break-all; overflow-wrap: break-word; white-space: pre-wrap; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console-heading" style="box-sizing: border-box; padding: 0px; margin: 1.5rem 0px 0.5rem; color: rgb(152, 168, 185); font: inherit;">채점을 시작합니다.</div><div class="console-message" style="box-sizing: border-box; padding: 0px; margin: 0.25rem 0px; color: rgb(95, 127, 144); font: inherit;">정확성  테스트</div>
테스트 1 〉 | 통과 (0.06ms, 10.4MB)
-- | --
테스트 2 〉 | 통과 (0.37ms, 10.3MB)
테스트 3 〉 | 통과 (1.71ms, 10.6MB)
테스트 4 〉 | 통과 (1.19ms, 10.3MB)
테스트 5 〉 | 통과 (0.03ms, 10.3MB)
테스트 6 〉 | 통과 (1.51ms, 10.6MB)
테스트 7 〉 | 통과 (1.64ms, 10.5MB)
테스트 8 〉 | 통과 (0.71ms, 10.3MB)
테스트 9 〉 | 통과 (0.65ms, 10.3MB)
테스트 10 〉 | 통과 (1.25ms, 10.4MB)
테스트 11 〉 | 통과 (1.95ms, 10.6MB)
테스트 12 〉 | 통과 (1.74ms, 10.6MB)
테스트 13 〉 | 통과 (0.33ms, 10.3MB)
테스트 14 〉 | 통과 (1.50ms, 10.5MB)
테스트 15 〉 | 통과 (3.26ms, 10.5MB)
테스트 16 〉 | 통과 (0.70ms, 10.3MB)
테스트 17 〉 | 통과 (1.99ms, 10.6MB)
테스트 18 〉 | 통과 (1.19ms, 10.4MB)
테스트 19 〉 | 통과 (1.73ms, 10.8MB)

<div class="console-heading" style="box-sizing: border-box; padding: 0px; margin: 1.5rem 0px 0.5rem; color: rgb(152, 168, 185); font: inherit;">채점 결과</div><div class="console-message" style="box-sizing: border-box; padding: 0px; margin: 0.25rem 0px; color: rgb(95, 127, 144); font: inherit;">정확성: 100.0</div><div class="console-message" style="box-sizing: border-box; padding: 0px; margin: 0.25rem 0px; color: rgb(95, 127, 144); font: inherit;">합계: 100.0 / 100.0</div></pre>
</body>
</html>

## 사용한 모듈
`heapq`

## 추가 정보
- 시간: 20 min 이하
- 힌트: `None`

2024-06-17 15:32 UTC, byeol3325 approved these changes
저랑 비슷하게 푸셨네요. 확인했습니다

2024-06-18 01:32 UTC, ksumini approved these changes

2024-06-18 01:32 UTC, ksumini commented on Programmers/호텔 대실/heewon.py
> +        answer = max(answer, len(room)) # 동시 예약된 호텔의 최대 개수 갱신
이 부분을 저는 53번째 조건문에서 걸리지 않는 경우는 힙이 비어있거나, 사용할 수 없는 객실이 없어 새로운 객실을 추가해야하기 때문에 else 문으로 항상 answer += 1를 해주게끔 했어요! 그렇게하면 for문 순회마다 max로 answer를 갱신할 필요가 없습니당..!

2024-06-18 01:32 UTC, ksumini commented on Programmers/호텔 대실/heewon.py
> +def timetomin(time:str)->int:
이 부분 함수로 뺀 것 까지 저랑 거의 코드가 유사해서 이해하기 쉬웠습니다 고생하셨습니다~!

2024-06-18 06:25 UTC, blaire-pi requested changes

2024-06-18 06:25 UTC, blaire-pi commented on Programmers/호텔 대실/heewon.py
> +        if room and start >= heap[0]:         # 대여 중이고 새로운 손님의 시작 시간 >= 기존 손님의 퇴실 시간
heap[0]이 아니라 room[0]이 되어야 할 거 같습니다.
저는 첫 예약인 경우를 위해 조건식을 따로 만들었는데 그럴 필요없이 이렇게 단축시킬 수도 있겠네요!

2024-06-18 11:47 UTC, c0natus approved these changes
heapq를 생각 못 했는데 활용해서 한 부분 알아 갑니다

2024-06-18 15:27 UTC, merged