[2024-08-08] sungho #191
ksumini/Algorithm-Study2.0 pull request #197
Opened 2024-08-07 14:36 UTC by byeol3325

< 풀이 시간 > 
30분

< 문제 회고 및 풀이 >
계산해보니까 50점과 60점, 20점 중에 점수가 정해진 sort에 따라 전처리하면 돼서 그렇게 문제 풀었다. 

# 테스트 결과
| 테스트 번호 | 결과  | 실행 시간 | 메모리 사용량 |
|-------------|-------|-----------|---------------|
| 테스트 1    | 통과  | 0.01ms    | 10.3MB        |
| 테스트 2    | 통과  | 184.22ms  | 29.2MB        |
| 테스트 3    | 통과  | 126.08ms  | 21.1MB        |
| 테스트 4    | 통과  | 127.17ms  | 21.2MB        |
| 테스트 5    | 통과  | 161.31ms  | 22.7MB        |
| 테스트 6    | 통과  | 142.07ms  | 22.1MB        |
| 테스트 7    | 통과  | 143.01ms  | 22.3MB        |
| 테스트 8    | 통과  | 9.07ms    | 10.6MB        |
| 테스트 9    | 통과  | 150.18ms  | 22.8MB        |
| 테스트 10   | 통과  | 26.13ms   | 12.1MB        |
| 테스트 11   | 통과  | 29.81ms   | 12.3MB        |
| 테스트 12   | 통과  | 169.41ms  | 23.6MB        |
| 테스트 13   | 통과  | 44.40ms   | 14.3MB        |
| 테스트 14   | 통과  | 180.96ms  | 29.2MB        |
| 테스트 15   | 통과  | 125.75ms  | 21MB          |
| 테스트 16   | 통과  | 26.94ms   | 12.1MB        |
| 테스트 17   | 통과  | 18.06ms   | 11.3MB        |
| 테스트 18   | 통과  | 171.01ms  | 23.8MB        |
| 테스트 19   | 통과  | 74.32ms   | 16.3MB        |
| 테스트 20   | 통과  | 203.49ms  | 29.2MB        |
| 테스트 21   | 통과  | 0.03ms    | 10.4MB        |
| 테스트 22   | 통과  | 0.05ms    | 10.4MB        |
| 테스트 23   | 통과  | 0.01ms    | 10.2MB        |
| 테스트 24   | 통과  | 0.07ms    | 10.4MB        |
| 테스트 25   | 통과  | 0.01ms    | 10.3MB        |

2024-08-08 04:33 UTC, HeewonKwak reviewed
해당 코드는 주어진 히든 케이스에 대해서는 올바르게 작동하지만, target 값이 247이고 answer가 [5, 3]인 경우에는 [5, 2] 결과가 나옵니다.

50, 50, 50, 57, 40과 같이 다트를 던지면 [5, 3]이 맞습니다.

2024-08-13 12:18 UTC, HeewonKwak approved these changes

2024-08-13 12:31 UTC, c0natus approved these changes

2024-08-13 12:42 UTC, ksumini requested changes

2024-08-13 12:42 UTC, ksumini commented on Programmers/카운트 다운/sungho.py
> +        candidates.append([NUM_DICT[i - 60][0] + 1, NUM_DICT[i - 60][1]]) # 현재점수-60에서 60점 1발 맞췄을 때
성호님, 번거로우시겠지만 희원님이 발견해주신 반례를 위해 코드 수정해서 다시 커밋해주시면 감사하겠습니다~!!

2024-08-22 12:01 UTC, ksumini approved these changes

2024-08-23 05:56 UTC, blaire-pi approved these changes
확인했습니다!!

2024-08-23 06:47 UTC, merged