[2024-08-13] yerin #200
ksumini/Algorithm-Study2.0 pull request #204
Opened 2024-08-13 02:08 UTC by blaire-pi

### PR Summary
<풀이 시간>
30분

<문제 회고>
예제를 보면서 문제 내용을 파악했다. 복잡하지는 않은 문제였다. 속도나 메모리 사용에서 내 위치를 파악할 수 있다보니 오기가 생기는 느낌이다.

[런타임 159ms / 메모리 17.80MB]

2024-08-13 04:34 UTC, HeewonKwak approved these changes
직접 문제처럼 배치하는 과정도 고려하셔서 문제를 푸셨군요 수고하셨습니다.

2024-08-13 04:34 UTC, HeewonKwak commented on Leetcode/Minimum Number of Pushes to Type Word II/yerin.py
> +        for alph, cnt in counter_alphabet_sort:
`alph` 변수는 사용 안 하니 `_`로 수정하면 좋겠다고 생각합니다.

2024-08-13 11:32 UTC, byeol3325 approved these changes

2024-08-13 11:32 UTC, byeol3325 commented on Leetcode/Minimum Number of Pushes to Type Word II/yerin.py
> +        counter_alphabet_sort = sorted(counter_alphabet.items(), key=lambda x: x[1], reverse= True)
갯수가 많은 순 아닌가요

2024-08-13 11:35 UTC, blaire-pi commented on Leetcode/Minimum Number of Pushes to Type Word II/yerin.py
> +        counter_alphabet_sort = sorted(counter_alphabet.items(), key=lambda x: x[1], reverse= True)
주석을 수정한다는 걸 깜빡했네요..! 알려주셔서 감사함다

2024-08-13 12:37 UTC, ksumini requested changes
예린님! 
LeetCode/3016/yerin.py

이걸로 해주시면 감사하겠습니다 :)

2024-08-13 12:38 UTC, ksumini requested changes

2024-08-13 12:38 UTC, ksumini commented on Leetcode/3016/yerin.py
> +from collections import Counter, defaultdict
예린님, defaultdict는 쓰이지 않으니까 지워도 될 것 같아요 :)

2024-08-26 05:26 UTC, ksumini approved these changes

2024-08-26 19:44 UTC, merged