[2024-08-22] sumin #208
ksumini/Algorithm-Study2.0 pull request #218
Opened 2024-08-22 07:59 UTC by ksumini

### PR Summary

**<풀이 시간>**
20분

<img width="735" alt="image" src="https://github.com/user-attachments/assets/22b1d284-4486-4f1b-9f11-8027242d09be">  

어렵지 않은 투포인터 문제

2024-08-22 08:09 UTC, blaire-pi requested changes
수민님 파일이 업로드가 안된 거 같아요! 확인부탁드립니다~

2024-08-22 08:11 UTC, ksumini commented
> 수민님 파일이 업로드가 안된 거 같아요! 확인부탁드립니다~

정신머리;; 감사합니다 예린님!!

2024-08-22 10:54 UTC, c0natus approved these changes
저는 while문 두개 썼는데 굳이 필요 없었네요

2024-08-22 11:47 UTC, byeol3325 approved these changes
투 포인터 풀이 잘 봤습니다 감사합니다

2024-08-22 13:28 UTC, HeewonKwak approved these changes
풀이가 비슷해서 쉽게 이해했습니다. 수민님 수고하셨습니다. 화이팅입니다.

2024-08-23 06:05 UTC, blaire-pi approved these changes
투포인터 풀이 배워갑니다! 저는 index랑 슬라이싱을 사용했는데, 왼쪽부터 차례로 없애나가는 게 좀 더 효율적이겠네요!

2024-08-26 05:27 UTC, merged