[2024-09-10] heewon #239
ksumini/Algorithm-Study2.0 pull request #248
Opened 2024-09-09 09:28 UTC by HeewonKwak

## 접근 방법
- 투 포인터
- 서로 양 끝에서 시작하는 경우는 처음이라 힌트를 참고하여 풀었다.
- 조건을 생각하고 구현하지 못 한 점이 아쉽다

![image](https://github.com/user-attachments/assets/39fe1a72-8403-4489-88b2-b35b0e824a16)

2024-09-10 09:11 UTC, byeol3325 approved these changes
저랑 똑같이 푸셨네요 고생하셨습니다!

2024-09-10 11:00 UTC, ksumini commented
풀이가 유사해 이해하기 쉬웠습니다! 백준에 투포인터 각 끝에서 시작하는 문제들 꽤 많은데 풀어보시면 좋을 거 같아요 희원님!!

2024-09-10 11:00 UTC, ksumini approved these changes

2024-09-10 11:14 UTC, c0natus approved these changes
저와 풀이가 유사해 이해하기 쉬웠습니다

2024-09-11 15:21 UTC, blaire-pi requested changes

2024-09-11 15:21 UTC, blaire-pi commented on LeetCode/11/heewon.py
> +                answer = max(answer, (right-left) * height[right])
여기서 너비 구하는 식이 `(left - right) * height[right]`가 되어야 하지 않나용?

2024-09-11 15:24 UTC, blaire-pi approved these changes
투포인터로 잘 푸신 것 같아요! 풀이보고 저도 배워갑니다

2024-09-12 14:12 UTC, merged