Create CodeTree 나무 타이쿤 hyoungrak.py
ksumini/Algorithm-Study2.0 pull request #291
Opened 2024-10-09 17:09 UTC by sjhh4

문제를 해결하지 못했습니다.
어디서 에러가 났는지 찾지 못했습니다 ㅠ
일단 업로드 합니다

문제 링크: 
https://www.codetree.ai/training-field/frequent-problems/problems/tree-tycoon/description?page=1&pageSize=20&tier=11%2C11

풀이시간: 2시간 (해결 못함)

### PR Summary

### ISSUE NUMBER

- #289

2024-10-10 06:22 UTC, ksumini commented
형락님, pr 옆에 reviewr랑 assignees, labels 추가 해주세요!

2024-10-10 07:21 UTC, ksumini requested changes

2024-10-10 07:21 UTC, ksumini commented on CodeTree/나무 타이쿤/hyoungrak.py
> +        try:  # 좌표 index가 0 이상 n-1 이하에 존재하는 곳만 체크하려고 try 써줌
위에서 만드신 방향 좌표중에 대각선 방향에 해당하는 좌표를 사용하시는 걸 추천드려요!

2024-10-10 07:21 UTC, ksumini commented on CodeTree/나무 타이쿤/hyoungrak.py
> +        nnmap[medicine[i][0]][medicine[i][1]] += grow  # 인접 대각에서 높이가 1 이상인 것 만큼 자라기
이 로직 부분 자체가 잘못됐습니다.
for 문으로 nnmap[medicine[i][0]][medicine[i][1]] += grow 이렇게 처리하면 이 변경된 높이가 다른 좌표의 대각선 값이라 영향을 줄 수 있죠? 동시에 어떻게 처리할 지 생각해보시면 좋을 것 같습니다

2024-10-10 10:36 UTC, sjhh4 commented on CodeTree/나무 타이쿤/hyoungrak.py
> +        nnmap[medicine[i][0]][medicine[i][1]] += grow  # 인접 대각에서 높이가 1 이상인 것 만큼 자라기
아... 맞네요 그 생각을 못했네요. 감사합니다!

2024-10-10 10:40 UTC, sjhh4 commented on CodeTree/나무 타이쿤/hyoungrak.py
> +        try:  # 좌표 index가 0 이상 n-1 이하에 존재하는 곳만 체크하려고 try 써줌
오 감사합니다! try 구문이 임시방편으로 처리하는 것으로 보일 수 있겠네요. 의견 감사해요!

2024-10-10 11:37 UTC, HeewonKwak requested changes

2024-10-12 15:45 UTC, sjhh4 commented on CodeTree/나무 타이쿤/hyoungrak.py
> +        nnmap[medicine[i][0]][medicine[i][1]] += grow  # 인접 대각에서 높이가 1 이상인 것 만큼 자라기
방금 풀었습니다! ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ

2024-10-12 15:47 UTC, sjhh4 commented on CodeTree/나무 타이쿤/hyoungrak.py
> +                if nnmap[i][j] >= 2:
ㅎㅎ 다음에는 간단한 if문 두개 이어질 경우 and로 한줄 표현 습관화 해야겠어요.
혼자 보기 좋은 코드가 아니라 다른 사람이 보기에도 좋은 코드로...!

2024-10-18 15:36 UTC, HeewonKwak approved these changes

2024-10-28 01:56 UTC, closed without merging