Sungho #329
ksumini/Algorithm-Study2.0 pull request #334
Opened 2024-11-07 11:00 UTC by byeol3325

### PR Summary

### ISSUE NUMBER

- #0

2024-11-07 12:31 UTC, ksumini requested changes

2024-11-07 12:31 UTC, ksumini commented on LeetCode/17/sungho.py
> +        outputs = []
outputs가 사용되지 않아서 이 부분 지워줘도 될 것 같아요!!

2024-11-07 13:27 UTC, c0natus approved these changes
product와 유사한 방식이라 이해하기 쉬웠습니다

2024-11-14 02:40 UTC, blaire-pi approved these changes
숫자 제한이 적은 경우 이렇게 코드를 짜는 것이 빠르다고 듣긴했는데 메모리도 더 적게 드네용..! 고생하셨습니다~

2024-11-14 12:15 UTC, ksumini approved these changes

2024-11-14 12:15 UTC, merged