Create [2024-06-04]: 혼자서 하는 틱택토 sungho.py
ksumini/Algorithm-Study2.0 pull request #80
Opened 2024-06-02 16:26 UTC by byeol3325

### PR Summary

### ISSUE NUMBER

- #0

2024-06-03 02:28 UTC, ksumini commented
제목을 [2024-06-04] sungho #78 로 변경해주세요~!

2024-06-03 02:32 UTC, ksumini approved these changes

2024-06-03 11:50 UTC, HeewonKwak approved these changes
수민님과 비슷한 접근법이기도 하고, 가독성이 좋은 코드 잘 보았습니다.

2024-06-03 11:50 UTC, HeewonKwak commented on sungho.py
> +        if A == board[i][0] == board[i][1] == board[i][2]:
구조적으로 비슷한 코드가 반복되는 것 같아서, 모듈화를 하면 좋겠다는 생각이 듭니다.

2024-06-03 13:44 UTC, c0natus approved these changes
가독성이 좋고, 최적화가 잘 되어 있는 것 같습니다.

2024-06-03 13:44 UTC, c0natus commented on sungho.py
> +        if A == board[i][0] == board[i][1] == board[i][2]:
==을 이렇게 사용할 수도 있다는 것을 배웠습니다.

2024-06-04 08:19 UTC, blaire-pi approved these changes

2024-06-04 08:19 UTC, blaire-pi commented on sungho.py
> +        if A == board[i][0] == board[i][1] == board[i][2]:
복수의 ==을 사용하여 조건식을 쓸 수 있다는 점 배우고 갑니다.

2024-06-04 08:19 UTC, blaire-pi commented on sungho.py
> +        if A == board[i][0] == board[i][1] == board[i][2]:
오 그렇네요. 좋은 아이디어 덕분에 배워갑니다.

2024-06-04 09:23 UTC, ksumini commented
성호님, 파일 경로 바꿔주세요! Programmers/혼자서 하는 틱택토/sungho.py 로 해서 다시 커밋해주시면 됩니다!

2024-06-05 02:05 UTC, ksumini requested changes
요청드린 변경사항 변경해주시면 Approve로 변경하겠습니다!

2024-06-06 03:04 UTC, ksumini approved these changes

2024-06-06 05:07 UTC, HeewonKwak reviewed
성호님 기존의 sungho.py 파일 제거해 주세요

2024-06-06 06:27 UTC, HeewonKwak approved these changes

2024-06-06 06:27 UTC, byeol3325 reviewed
finish

2024-06-06 06:44 UTC, byeol3325 commented on sungho.py
> +        if A == board[i][0] == board[i][1] == board[i][2]:
감사합니다

2024-06-06 06:45 UTC, byeol3325 commented on sungho.py
> +        if A == board[i][0] == board[i][1] == board[i][2]:
감사합니다

2024-06-06 06:45 UTC, byeol3325 commented on sungho.py
> +        if A == board[i][0] == board[i][1] == board[i][2]:
감사합니다.

2024-06-10 03:44 UTC, merged