[2024-06-06] yerin #84
ksumini/Algorithm-Study2.0 pull request #87
Opened 2024-06-05 20:02 UTC by blaire-pi

### PR Summary

<풀이시간>
약 80분

<문제 회고>
문제 접근 방식을 머리로만 생각하고 코드를 짜지 않고, 주석을 달아 정리하는 시간을 가지니 코드를 작성하는데 걸리는 시간을 단축시킬 수 있었다.

구현 방식은 다음과 같다.
1. 십진수를 이진수로 변환. 생략되었을지도 모르는 더미노드 수만큼 '0'을 앞에 붙여, 여러 개의 가능한 경우를 생성
2. 생성된 경우에 대하여 포화 이진트리 만족 여부를 체크. 
    - 부모 노드가 0일 때 1인 자식 노드가 있으면 안됨
    - 하위 노드 개수는 항상 홀수
3. 여러 경우에 대한 결과값을 임시 리스트에 저장. 하나의 경우라도 포화 이진트리를 만족할 시 1을 반환

본 문제에서 반례를 찾는 일이 머리가 아팠다. 첫 번째 조건에 집중한 나머지 두 번째 조건을 알아차리지 못했다. 따로 트리에 대해 찾아보지 않고 문제 내용만 보고 이해한대로 풀어내다보니 트리가 가진 특징을 코드에 녹여내지 못한 것 같아 아쉬움이 남는다.

Case | Complexity
-- | --
테스트 1 〉 | 통과 (0.02ms, 10.3MB)
테스트 2 〉 | 통과 (0.03ms, 10.3MB)
테스트 3 〉 | 통과 (0.07ms, 10.4MB)
테스트 4 〉 | 통과 (0.27ms, 10.2MB)
테스트 5 〉 | 통과 (0.56ms, 10.2MB)
테스트 6 〉 | 통과 (0.98ms, 10.2MB)
테스트 7 〉 | 통과 (1.54ms, 10.4MB)
테스트 8 〉 | 통과 (1.07ms, 10.2MB)
테스트 9 〉 | 통과 (9.86ms, 10.3MB)
테스트 10 〉 | 통과 (92.01ms, 11MB)
테스트 11 〉 | 통과 (97.83ms, 11.4MB)
테스트 12 〉 | 통과 (97.98ms, 11.1MB)
테스트 13 〉 | 통과 (85.70ms, 11MB)
테스트 14 〉 | 통과 (76.35ms, 10.9MB)
테스트 15 〉 | 통과 (62.59ms, 10.7MB)
테스트 16 〉 | 통과 (166.37ms, 11.3MB)
테스트 17 〉 | 통과 (167.56ms, 11.3MB)
테스트 18 〉 | 통과 (142.81ms, 11.1MB)
테스트 19 〉 | 통과 (143.25ms, 10.9MB)
테스트 20 〉 | 통과 (89.65ms, 10.7MB)

</pre>
</body>
</html>

2024-06-06 01:50 UTC, byeol3325 reviewed
코드에도 주석을 넣어주시면 더 좋을 거 같아요

2024-06-06 01:50 UTC, byeol3325 commented on Programmers/표현 가능한 이진트리/yerin.py
> +        bin_num = format(num, 'b')
bin(num)으로도 2진수로 바꿀 수 있습니다. 참고하시면 좋을 거 같아요. 저도 format 익혀갑니다

2024-06-06 01:50 UTC, byeol3325 commented on Programmers/표현 가능한 이진트리/yerin.py
> +        s, e = queue.pop(0)
pop을 이용해서 푸시려면 deque 이용하시면 더 시간 줄일 수 있을거에요

2024-06-06 05:56 UTC, HeewonKwak requested changes
주어진 테스트 케이스에서는 정답이 나왔지만, 제가 생각한 반례(31)를 통과하지 못하는 코드라고 생각합니다.

2024-06-06 05:56 UTC, HeewonKwak commented on Programmers/표현 가능한 이진트리/yerin.py
> +        bin_num = format(num, 'b') #앞에 접두어 제거를 위해 format 사용
format 배웁니다

2024-06-06 05:56 UTC, HeewonKwak commented on Programmers/표현 가능한 이진트리/yerin.py
> +            continue
저는 모든 문자가 '1'일 때, 항상 포화 이진트리 조건을 만족한다고 생각하지 않습니다.
반례로 31을 이진수로 표현한 11111이 있습니다.

2024-06-06 06:38 UTC, ksumini requested changes

2024-06-06 06:38 UTC, ksumini commented on Programmers/표현 가능한 이진트리/yerin.py
> +            continue
저도 이 부분, 테스트 케이스가 부족해서 통과되는 코드 같아요.
모든 문자가 1이라고 하더라도 무조건 포화 이진트리 조건을 충족하지 않아요!
희원님이 올려주신 31의 경우 답은 1이 아니라 0이 나와야 될 것 같습니다!

2024-06-06 06:48 UTC, byeol3325 approved these changes
확인했습니다.

2024-06-06 06:58 UTC, blaire-pi commented on Programmers/표현 가능한 이진트리/yerin.py
> +            continue
오 해당 반례를 생각하지 못했네요. 알려주셔서 감사합니다.

2024-06-06 08:18 UTC, c0natus approved these changes

2024-06-06 08:18 UTC, c0natus commented on Programmers/표현 가능한 이진트리/yerin.py
> +- 한 숫자에 여러 경우가 존재할 수 있으니 임의 리스트에 결과값을 저장. 그 중 하나의 경우라도 포화 이진트리로 만들어질 수 있다면(즉, 1이 존재한다면) answer에 1 삽입
저는 한 숫자는 한 경우의 수밖에 안 된다고 생각했는데, 한 숫자에 여러 경우의 수가 생기는 예시를 들어주시면 좋을 것 같습니다!

2024-06-06 12:28 UTC, HeewonKwak approved these changes

2024-06-10 13:13 UTC, ksumini approved these changes

2024-06-11 08:02 UTC, merged